// Generated by delombok at Sat Feb 25 09:19:10 PST 2017
package astraeus.game.model.widget.dialog;

/**
 * The {@link Chainable} implementation that represents dialogue in which an NPC is talking.
 *
 * @author Vult-R
 */
public final class NpcDialogue implements Chainable {
  
  /**
   * The id of this npc.
   */
  private int id = -1;
  
  /**
   * The expression of this NPC.
   */
  private final Expression expression;
  
  /**
   * The text for this dialogue.
   */
  private final String[] lines;

  /**
   * Creates a new {@link NpcDialogue}
   *
   * @param lines The text for this dialogue.
   */
  public NpcDialogue(String... lines) {
    this(Expression.DEFAULT, lines);
  }

  /**
   * Creates a new {@link NpcDialogue}
   *
   * @param expression The expression of this npc.
   *
   * @param lines The text for this dialogue.
   */
  public NpcDialogue(Expression expression, String... lines) {
    this.expression = expression;
    this.lines = lines;
  }

  /**
   * Creates a new {@link NpcDialogue}
   *
   * @param id The id of this npc.
   *
   * @param lines The text for this dialogue.
   */
  public NpcDialogue(int id, String... lines) {
    this(id, Expression.DEFAULT, lines);
  }

  /**
   * Creates a new {@link NpcDialogue}
   *
   * @param id The id of this npc.
   *
   * @param expression The expression of this npc.
   *
   * @param lines The text for this dialogue.
   */
  public NpcDialogue(int id, Expression expression, String... lines) {
    this.id = id;
    this.expression = expression;
    this.lines = lines;
  }

  @Override
  public void accept(DialogueFactory factory) {
    factory.sendNpcChat(this);
  }

  /**
   * The id of this npc.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getId() {
    return this.id;
  }

  /**
   * The expression of this NPC.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public Expression getExpression() {
    return this.expression;
  }

  /**
   * The text for this dialogue.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public String[] getLines() {
    return this.lines;
  }

  /**
   * The id of this npc.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public void setId(final int id) {
    this.id = id;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof NpcDialogue)) return false;
    final NpcDialogue other = (NpcDialogue)o;
    if (this.getId() != other.getId()) return false;
    final java.lang.Object this$expression = this.getExpression();
    final java.lang.Object other$expression = other.getExpression();
    if (this$expression == null ? other$expression != null : !this$expression.equals(other$expression)) return false;
    if (!java.util.Arrays.deepEquals(this.getLines(), other.getLines())) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.getId();
    final java.lang.Object $expression = this.getExpression();
    result = result * PRIME + ($expression == null ? 0 : $expression.hashCode());
    result = result * PRIME + java.util.Arrays.deepHashCode(this.getLines());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public java.lang.String toString() {
    return "NpcDialogue(id=" + this.getId() + ", expression=" + this.getExpression() + ", lines=" + java.util.Arrays.deepToString(this.getLines()) + ")";
  }
}