// Generated by delombok at Sat Feb 25 09:19:10 PST 2017
package astraeus.game.model.widget.dialog;

/**
 * A {@link Chainable} implementation that represents a player talking.
 *
 * @author Vult-R
 */
public class PlayerDialogue implements Chainable {
  
  /**
   * The expression of this player.
   */
  private final Expression expression;
  
  /**
   * The text for this dialogue.
   */
  private final String[] lines;

  /**
   * Creates a new {@link PlayerDialogue} with a default expression of {@code DEFAULT}.
   *
   * @param lines The text for this dialogue.
   */
  public PlayerDialogue(String... lines) {
    this(Expression.DEFAULT, lines);
  }

  /**
   * Creates a new {@link PlayerDialogue}.
   *
   * @param expression The expression for this dialogue.
   *
   * @param lines The text for this dialogue.
   */
  public PlayerDialogue(Expression expression, String... lines) {
    this.expression = expression;
    this.lines = lines;
  }

  @Override
  public void accept(DialogueFactory factory) {
    factory.sendPlayerChat(this);
  }

  /**
   * The expression of this player.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public Expression getExpression() {
    return this.expression;
  }

  /**
   * The text for this dialogue.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public String[] getLines() {
    return this.lines;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof PlayerDialogue)) return false;
    final PlayerDialogue other = (PlayerDialogue)o;
    if (!other.canEqual((java.lang.Object)this)) return false;
    final java.lang.Object this$expression = this.getExpression();
    final java.lang.Object other$expression = other.getExpression();
    if (this$expression == null ? other$expression != null : !this$expression.equals(other$expression)) return false;
    if (!java.util.Arrays.deepEquals(this.getLines(), other.getLines())) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof PlayerDialogue;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $expression = this.getExpression();
    result = result * PRIME + ($expression == null ? 0 : $expression.hashCode());
    result = result * PRIME + java.util.Arrays.deepHashCode(this.getLines());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public java.lang.String toString() {
    return "PlayerDialogue(expression=" + this.getExpression() + ", lines=" + java.util.Arrays.deepToString(this.getLines()) + ")";
  }
}