// Generated by delombok at Sat Feb 25 09:19:11 PST 2017
package astraeus.game.model.widget.dialog;

/**
 * The {@link Chainable} implementation that represents a dialogue with a single statement; which
 * has no models on the dialogue.
 *
 * @author Vult-R
 */
public class StatementDialogue implements Chainable {
  
  /**
   * The text for this dialogue.
   */
  private final String[] lines;

  /**
   * Creates a new {@link StatementDialogue}.
   *
   * @param lines The text for this dialogue.
   */
  public StatementDialogue(String... lines) {
    this.lines = lines;
  }

  @Override
  public void accept(DialogueFactory factory) {
    factory.sendStatement(this);
  }

  /**
   * The text for this dialogue.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public String[] getLines() {
    return this.lines;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof StatementDialogue)) return false;
    final StatementDialogue other = (StatementDialogue)o;
    if (!other.canEqual((java.lang.Object)this)) return false;
    if (!java.util.Arrays.deepEquals(this.getLines(), other.getLines())) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof StatementDialogue;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + java.util.Arrays.deepHashCode(this.getLines());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public java.lang.String toString() {
    return "StatementDialogue(lines=" + java.util.Arrays.deepToString(this.getLines()) + ")";
  }
}