// Generated by delombok at Sat Feb 25 09:19:10 PST 2017
package astraeus.game.model.sound;

/**
 * Represents a single song that can be played in-game.
 *
 * @author Seven
 */
public final class Song {
  
  /**
   * The id of this song.
   */
  private final int id;
  
  /**
   * The name of this song.
   */
  private final String name;
  
  /**
   * The regions this song is found in.
   */
  private final int[] region;

  /**
   * Creates a new {@link Song}.
   *
   * @param id The id of this song.
   *
   * @param name The name of this song.
   *
   * @param region The regions this song is played in.
   */
  public Song(int id, String name, int[] region) {
    this.id = id;
    this.name = name;
    this.region = region;
  }

  /**
   * The id of this song.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getId() {
    return this.id;
  }

  /**
   * The name of this song.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public String getName() {
    return this.name;
  }

  /**
   * The regions this song is found in.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int[] getRegion() {
    return this.region;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Song)) return false;
    final Song other = (Song)o;
    if (this.getId() != other.getId()) return false;
    final java.lang.Object this$name = this.getName();
    final java.lang.Object other$name = other.getName();
    if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
    if (!java.util.Arrays.equals(this.getRegion(), other.getRegion())) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.getId();
    final java.lang.Object $name = this.getName();
    result = result * PRIME + ($name == null ? 0 : $name.hashCode());
    result = result * PRIME + java.util.Arrays.hashCode(this.getRegion());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public java.lang.String toString() {
    return "Song(id=" + this.getId() + ", name=" + this.getName() + ", region=" + java.util.Arrays.toString(this.getRegion()) + ")";
  }
}