// Generated by delombok at Sat Feb 25 09:19:06 PST 2017
package astraeus.game.model.entity.mob.combat.dmg;

/**
 * Represents a hitsplat
 *
 * @author Vult-R
 */
public final class Hit {
  private int damage;
  private HitType type;
  private DamageType damageType;
  private boolean isSecond;
  private boolean enabled;
  
  public Hit(int damage) {
    this(damage, HitType.NORMAL, DamageType.NONE);
  }
  
  public Hit(int damage, DamageType damageType) {
    this(damage, HitType.NORMAL, damageType);
  }
  
  public Hit(int damage, HitType type, DamageType damageType) {
    this.damage = damage;
    this.type = type;
    this.damageType = damageType;
    if (this.damage == 0 && this.type == HitType.NORMAL) {
      this.type = HitType.BLOCKED;
    } else if (this.damage > 0 && this.type == HitType.BLOCKED) {
      this.damage = 0;
    } else if (this.damage < 0) {
      this.damage = 0;
    }
    enable();
  }
  
  public void setDamage(int damage) {
    this.damage = damage;
    if (damage == 0) {
      type = HitType.BLOCKED;
    } else if (damage < 0) {
      disable();
    }
  }
  
  public void disable() {
    enabled = false;
  }
  
  public void enable() {
    enabled = true;
  }
  
  @Override
  public Hit clone() {
    return new Hit(damage, type, damageType);
  }
  
  @Override
  public String toString() {
    return "[HIT] - Damage: " + getDamage() + " Type: " + getType().name();
  }
  
  @Override
  public boolean equals(Object other) {
    if (other == null || other.getClass() != Hit.class) {
      return false;
    }
    final Hit hit = (Hit)other;
    return hit.damage == damage && hit.type == type;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getDamage() {
    return this.damage;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public HitType getType() {
    return this.type;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public void setType(final HitType type) {
    this.type = type;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public DamageType getDamageType() {
    return this.damageType;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public void setDamageType(final DamageType damageType) {
    this.damageType = damageType;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public boolean isSecond() {
    return this.isSecond;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public void setSecond(final boolean isSecond) {
    this.isSecond = isSecond;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public boolean isEnabled() {
    return this.enabled;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public void setEnabled(final boolean enabled) {
    this.enabled = enabled;
  }
}