// Generated by delombok at Sat Feb 25 09:19:06 PST 2017
package astraeus.game.model.entity.mob.combat;

import astraeus.game.model.entity.mob.player.collect.Equipment;

/**
 * Represents an attack style.
 *
 * @author Vult-R
 */
public enum AttackStyle {
  STAB(Equipment.STAB, Equipment.STAB_DEFENSE),
  SLASH(Equipment.SLASH, Equipment.SLASH_DEFENSE),
  CRUSH(Equipment.CRUSH, Equipment.CRUSH_DEFENSE),
  RANGED(Equipment.RANGED, Equipment.RANGED_DEFENSE),
  MAGIC(Equipment.MAGIC, Equipment.MAGIC_DEFENSE);
  private int offensiveSlot;
  private int defensiveSlot;

  private AttackStyle(int offensiveSlot, int defensiveSlot) {
    this.offensiveSlot = offensiveSlot;
    this.defensiveSlot = defensiveSlot;
  }

  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getOffensiveSlot() {
    return this.offensiveSlot;
  }

  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getDefensiveSlot() {
    return this.defensiveSlot;
  }
}