// Generated by delombok at Sat Feb 25 09:19:06 PST 2017
package astraeus.game.model.entity.mob.combat;

public enum CombatType {
  MELEE(4),
  RANGE(4),
  MAGIC(2);
  private int rate;

  private CombatType(int rate) {
    this.rate = rate;
  }

  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getRate() {
    return this.rate;
  }
}