// Generated by delombok at Sat Feb 25 09:19:06 PST 2017
package astraeus.game.model.entity.mob.combat;

import astraeus.game.model.entity.mob.Mob;
import astraeus.game.task.Task;

/**
 * The {@link Task} that resets combat cooldowns.
 *
 * @author Vult-R
 */
public final class CooldownTask extends Task {
  private final Mob mob;
  private final CombatType cooldown;
  private final int delay;
  
  public CooldownTask(Mob mob, CombatType cooldown, int delay) {
    super(delay, false);
    this.mob = mob;
    this.cooldown = cooldown;
    this.delay = delay;
  }
  
  @Override
  public void execute() {
    if (tick >= delay) {
      mob.getCombat().getCombatCooldown().reset(cooldown);
      stop();
    }
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public Mob getMob() {
    return this.mob;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public CombatType getCooldown() {
    return this.cooldown;
  }
  
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getDelay() {
    return this.delay;
  }
}