// Generated by delombok at Sat Feb 25 09:19:05 PST 2017
package astraeus.game.model;

/**
 * The enumeration of the brightness levels as seen by the client.
 *
 * @author Vult-R
 */
public enum Brightness {
  VERY_DARK(1),
  DARK(2),
  NORMAL(3),
  BRIGHT(4);
  private final int code;

  private Brightness(int code) {
    this.code = code;
  }

  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getCode() {
    return this.code;
  }
}