// Generated by delombok at Sat Feb 25 09:19:07 PST 2017
package astraeus.game.model.entity.mob.player;

/**
 * Represents a {@link Player}s appearance.
 *
 * @author Vult-R
 */
public final class Appearance {

  /**
   * Represents the a gender model of a {@link Player}
   */
  public enum Gender {
    MALE(0),
    FEMALE(1);
    private int code;

    private Gender(final int id) {
      this.code = id;
    }

    public int getCode() {
      return code;
    }
  }
  
  /**
   * The gender of this player.
   */
  private final Gender gender;
  
  /**
   * The head model
   */
  private final int head;
  
  /**
   * The jaw model
   */
  private final int jaw;
  
  /**
   * The torso model
   */
  private final int torso;
  
  /**
   * The arms model
   */
  private final int arms;
  
  /**
   * The hands model
   */
  private final int hands;
  
  /**
   * The legs model
   */
  private final int legs;
  
  /**
   * The feet model
   */
  private final int feet;
  
  /**
   * The color of the hair model
   */
  private final int hairColor;
  
  /**
   * The color of the torso model
   */
  private final int torsoColor;
  
  /**
   * The color of the legs model
   */
  private final int legsColor;
  
  /**
   * The color of the feet model
   */
  private final int feetColor;
  
  /**
   * The color of skin
   */
  private final int skinColor;

  public Appearance(final Gender gender, final int head, final int jaw, final int torso, final int arms, final int hands, final int legs, final int feet, int hairColor, int torsoColor, int legsColor, int feetColor, int skinColor) {
    this.gender = gender;
    this.head = head;
    this.jaw = jaw;
    this.torso = torso;
    this.arms = arms;
    this.hands = hands;
    this.legs = legs;
    this.feet = feet;
    this.hairColor = hairColor;
    this.torsoColor = torsoColor;
    this.legsColor = legsColor;
    this.feetColor = feetColor;
    this.skinColor = skinColor;
  }

  public Appearance getDefaultAppearance() {
    return Player.DEFAULT_APPEARANCE;
  }

  @Override
  public String toString() {
    return "Gender: " + getGender().name() + " Head: " + getHead() + " Jaw: " + getJaw() + " Torso: " + getTorso() + " Arms: " + getArms() + " Hands: " + getHands() + " Legs: " + getLegs() + " feet: " + getFeet();
  }

  /**
   * The gender of this player.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public Gender getGender() {
    return this.gender;
  }

  /**
   * The head model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getHead() {
    return this.head;
  }

  /**
   * The jaw model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getJaw() {
    return this.jaw;
  }

  /**
   * The torso model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getTorso() {
    return this.torso;
  }

  /**
   * The arms model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getArms() {
    return this.arms;
  }

  /**
   * The hands model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getHands() {
    return this.hands;
  }

  /**
   * The legs model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getLegs() {
    return this.legs;
  }

  /**
   * The feet model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getFeet() {
    return this.feet;
  }

  /**
   * The color of the hair model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getHairColor() {
    return this.hairColor;
  }

  /**
   * The color of the torso model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getTorsoColor() {
    return this.torsoColor;
  }

  /**
   * The color of the legs model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getLegsColor() {
    return this.legsColor;
  }

  /**
   * The color of the feet model
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getFeetColor() {
    return this.feetColor;
  }

  /**
   * The color of skin
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getSkinColor() {
    return this.skinColor;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Appearance)) return false;
    final Appearance other = (Appearance)o;
    final java.lang.Object this$gender = this.getGender();
    final java.lang.Object other$gender = other.getGender();
    if (this$gender == null ? other$gender != null : !this$gender.equals(other$gender)) return false;
    if (this.getHead() != other.getHead()) return false;
    if (this.getJaw() != other.getJaw()) return false;
    if (this.getTorso() != other.getTorso()) return false;
    if (this.getArms() != other.getArms()) return false;
    if (this.getHands() != other.getHands()) return false;
    if (this.getLegs() != other.getLegs()) return false;
    if (this.getFeet() != other.getFeet()) return false;
    if (this.getHairColor() != other.getHairColor()) return false;
    if (this.getTorsoColor() != other.getTorsoColor()) return false;
    if (this.getLegsColor() != other.getLegsColor()) return false;
    if (this.getFeetColor() != other.getFeetColor()) return false;
    if (this.getSkinColor() != other.getSkinColor()) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $gender = this.getGender();
    result = result * PRIME + ($gender == null ? 0 : $gender.hashCode());
    result = result * PRIME + this.getHead();
    result = result * PRIME + this.getJaw();
    result = result * PRIME + this.getTorso();
    result = result * PRIME + this.getArms();
    result = result * PRIME + this.getHands();
    result = result * PRIME + this.getLegs();
    result = result * PRIME + this.getFeet();
    result = result * PRIME + this.getHairColor();
    result = result * PRIME + this.getTorsoColor();
    result = result * PRIME + this.getLegsColor();
    result = result * PRIME + this.getFeetColor();
    result = result * PRIME + this.getSkinColor();
    return result;
  }
}