// Generated by delombok at Sat Feb 25 09:19:08 PST 2017
package astraeus.game.model.entity.mob.player;

/**
 * The class that models a players chat message.
 *
 * @author Seven
 */
public final class ChatMessage {
  
  /**
   * The color of the text.
   */
  private final int color;
  
  /**
   * The client-sided effects.
   */
  private final int effect;
  
  /**
   * The array of characters.
   */
  private final byte[] text;

  /**
   * A default constructor for new players.
   */
  public ChatMessage() {
    this(0, 0, null);
  }

  /**
   * Creates a new {@link ChatMessage).
   *
   * @param color The color of this chat message.
   *
   * @param effect The client-sided effect of this message.
   *
   * @param text The text in data form.
   */
  public ChatMessage(int color, int effect, byte[] text) {
    this.color = color;
    this.effect = effect;
    this.text = text;
  }

  /**
   * The color of the text.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getColor() {
    return this.color;
  }

  /**
   * The client-sided effects.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getEffect() {
    return this.effect;
  }

  /**
   * The array of characters.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public byte[] getText() {
    return this.text;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof ChatMessage)) return false;
    final ChatMessage other = (ChatMessage)o;
    if (this.getColor() != other.getColor()) return false;
    if (this.getEffect() != other.getEffect()) return false;
    if (!java.util.Arrays.equals(this.getText(), other.getText())) return false;
    return true;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.getColor();
    result = result * PRIME + this.getEffect();
    result = result * PRIME + java.util.Arrays.hashCode(this.getText());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public java.lang.String toString() {
    return "ChatMessage(color=" + this.getColor() + ", effect=" + this.getEffect() + ", text=" + java.util.Arrays.toString(this.getText()) + ")";
  }
}