// Generated by delombok at Sat Feb 25 09:19:07 PST 2017
package astraeus.game.model.entity.mob.player.attr;

import java.util.Objects;

/**
 * Represents a single attribute.
 *
 * @author Ryley Kimmel <ryley.kimmel@live.com>
 *
 * @param <T> The attributes values type reference.
 */
final class Attribute<T> {
  
  /**
   * This attributes key. An attributes key is an identifier that encapsulates this attributes name.
   * This key is used for representing an attribute through some collection.
   */
  private final AttributeKey<T> key;
  
  /**
   * The value of this attribute, the type of value of this attribute is as described by this
   * classes parameter.
   *
   * @see {@link T}
   */
  private final T value;

  /**
   * Constructs a new {@link Attribute} with the specified key and value.
   *
   * @param key This attributes key, may not be {@code null}.
   * @param value This attributes value.
   */
  protected Attribute(AttributeKey<T> key, T value) {
    this.key = Objects.requireNonNull(key);
    this.value = value;
  }

  /**
   * This attributes key. An attributes key is an identifier that encapsulates this attributes name.
   * This key is used for representing an attribute through some collection.
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public AttributeKey<T> getKey() {
    return this.key;
  }

  /**
   * The value of this attribute, the type of value of this attribute is as described by this
   * classes parameter.
   *
   * @see {@link T}
   */
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public T getValue() {
    return this.value;
  }
}