// Generated by delombok at Sat Feb 25 09:19:09 PST 2017
package astraeus.game.model.entity.mob.player.skill;

/**
 * The skill-related requirement.
 *
 * @author SeVen
 */
public class SkillRequirement {
  private final int level;
  private final SkillData skill;

  public SkillRequirement(int level, SkillData skill) {
    this.level = level;
    this.skill = skill;
  }

  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int getLevel() {
    return this.level;
  }

  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public SkillData getSkill() {
    return this.skill;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof SkillRequirement)) return false;
    final SkillRequirement other = (SkillRequirement)o;
    if (!other.canEqual((java.lang.Object)this)) return false;
    if (this.getLevel() != other.getLevel()) return false;
    final java.lang.Object this$skill = this.getSkill();
    final java.lang.Object other$skill = other.getSkill();
    if (this$skill == null ? other$skill != null : !this$skill.equals(other$skill)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof SkillRequirement;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + this.getLevel();
    final java.lang.Object $skill = this.getSkill();
    result = result * PRIME + ($skill == null ? 0 : $skill.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @javax.annotation.Generated("lombok")
  public java.lang.String toString() {
    return "SkillRequirement(level=" + this.getLevel() + ", skill=" + this.getSkill() + ")";
  }
}